[package]
name = "l10nregistry"
version = "0.1.1"
authors = ["Zibi Braniecki <gandalf@mozilla.com>"]
license = "Apache-2.0/MIT"
edition = "2018"

[dependencies]
async-trait = "0.1"
chunky-vec = "0.1"
fluent-bundle = { path = "../fluent-rs/fluent-bundle" }
fluent-testing = { path = "../fluent-rs/fluent-testing", features = ["sync", "async"] }
fluent-fallback = { path = "../fluent-rs/fluent-fallback" }
futures = "0.3"
log = "0.4"
pin-project = "1.0"
unic-langid = "0.9"
tokio = { version = "1.0", optional = true, features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
unic-langid = { version = "0.9", features = ["macros"] }
serial_test = "0.5"
criterion = "0.3"

[features]
default = []
tokio-io = ["tokio"]

[[example]]
name = "async"
required-features = ["tokio"]

[[bench]]
name = "preferences"
harness = false
required-features = ["tokio"]

[[bench]]
name = "localization"
harness = false
required-features = ["tokio"]

[[bench]]
name = "solver"
harness = false

[[test]]
name = "source"
path = "tests/source.rs"
required-features = ["tokio"]

[[test]]
name = "registry"
path = "tests/registry.rs"
required-features = ["tokio"]

[[test]]
name = "localization"
path = "tests/localization.rs"
required-features = ["tokio"]
